--2
SET AUTOCOMMIT OFF 

--3
INSERT INTO EMP (ID, FIRST_NAME, LAST_NAME) VALUES(26, 'Sebastian', 'Tyda');

--4
INSERT INTO EMP (ID, FIRST_NAME, LAST_NAME, START_DATE, SALARY) VALUES(27, 'Marek', 'Tyda', '20/05/03', 5000);
SELECT * FROM EMP; -- Jestem pracownikiem!
ROLLBACK;
SELECT * FROM EMP; -- Chyba mnie wylali :((((((((((

--5
INSERT INTO EMP (ID, FIRST_NAME, LAST_NAME, START_DATE, SALARY) VALUES(27, 'Marek', 'Tyda', '20/05/03', 5000);
COMMIT; -- I znowu w pracy :)

--6
SELECT * FROM ITEM;
UPDATE ITEM SET PRICE = PRICE * 1.15;
SAVEPOINT S1;
SELECT SUM(PRICE) FROM ITEM; --12018
UPDATE ITEM SET PRICE = PRICE * 1.1;
SELECT SUM(PRICE) FROM ITEM; --13219,92
SAVEPOINT S2;
UPDATE ITEM SET PRICE = PRICE * 1.6;
SELECT SUM(PRICE) FROM ITEM; --21151,85
ROLLBACK TO SAVEPOINT S2;
SELECT SUM(PRICE) FROM ITEM; --13219,92
ROLLBACK TO SAVEPOINT S1;
SELECT SUM(PRICE) FROM ITEM; --12018
COMMIT;

--7
SET AUTOCOMMIT ON;

--8
CREATE TABLE REGION_COPY AS SELECT * FROM REGION;

--9
INSERT INTO DEPT SELECT ID+100, SUBSTR(NAME, 0, 4), REGION_ID FROM DEPT;

--10
-- Nie wiem czy dobrze zrozumiałem polecenie. Trochę jest niejasne.
INSERT INTO REGION_COPY SELECT CUSTOMER_ID, NAME FROM CUSTOMER, ORD
WHERE ORD.CUSTOMER_ID=CUSTOMER.ID
GROUP BY CUSTOMER_ID, NAME
HAVING MAX(TOTAL) > 1000;

--11
UPDATE EMP SET SALARY = SALARY * 4, START_DATE=TO_DATE('31-12-2001', 'dd-mm-yyyy') WHERE ID=27;

--12a
UPDATE PRODUCT
SET SUGGESTED_WHLSL_PRICE = SUGGESTED_WHLSL_PRICE * 0.9
WHERE ID IN (SELECT PRODUCT_ID FROM ITEM GROUP BY PRODUCT_ID HAVING SUM(QUANTITY) < 30);

--12b
UPDATE PRODUCT
SET SUGGESTED_WHLSL_PRICE = SUGGESTED_WHLSL_PRICE * 1.08
WHERE ID IN (SELECT PRODUCT_ID FROM (SELECT PRODUCT_ID, SUM(QUANTITY) FROM ITEM GROUP BY PRODUCT_ID ORDER BY SUM(QUANTITY) DESC) WHERE ROWNUM<=5);

--13
UPDATE EMP
SET SALARY = SALARY * 1.3
WHERE TITLE LIKE 'VP%';

--14
DELETE FROM EMP WHERE ID=27 OR ID=26;

--15
DROP TABLE REGION_COPY;