--1
SELECT LOWER(FIRST_NAME)"IMIĘ",LOWER(LAST_NAME)"NAZWISKO",INITCAP(USERID)"IDENTYFIKATOR",UPPER(TITLE)"STANOWISKO" FROM EMP
WHERE SUBSTR(TITLE,1,2)='VP';
--2
SELECT FIRST_NAME"IMIĘ",LAST_NAME"NAZWISKO"FROM EMP
WHERE UPPER(LAST_NAME)='PATEL';
--3
SELECT CONCAT(CONCAT(NAME,' - '),COUNTRY)"NAZWA i PAŃSTWO" FROM CUSTOMER
WHERE CREDIT_RATING='GOOD';
--4
SELECT NAME "NAZWA",LENGTH(NAME)"LICZBA ZNAKÓW"FROM PRODUCT
WHERE SUBSTR(NAME,1,3)='Ace';
--5
SELECT ROUND(41.5843,2)"SETNE",ROUND(41.5843,0)"CAŁKOWITE",ROUND(41.5843,-1)"DZIESIĄTKI"FROM DUAL;
--6
SELECT TRUNC(41.5843,2)"SETNE",TRUNC(41.5843,0)"CAŁKOWITE",TRUNC(41.5843,-1)"DZIESIĄTKI"FROM DUAL;
--7
SELECT LAST_NAME"NAZWISKO",MOD(SALARY,COMMISSION_PCT)"RESZTA"FROM EMP
WHERE SALARY>=1380;
--7a --Wystarczy się upewnić, że COMMISSION_PCT nie będzie NULLEM
SELECT LAST_NAME"NAZWISKO",MOD(SALARY,COMMISSION_PCT)"RESZTA"FROM EMP
WHERE SALARY>=1380 AND NOT COMMISSION_PCT IS NULL;
--8
SELECT CONCAT(TO_CHAR(SYSDATE,'DD/MM/YY'),'     ')"AKTUALNA DATA" FROM DUAL;
--9
SELECT LAST_NAME "NAZWISKO" ,TRUNC(((SYSDATE-START_DATE)/7),0) "Tygodnie" FROM EMP
WHERE DEPT_ID=43;
--10
SELECT ID,TRUNC(MONTHS_BETWEEN(SYSDATE,START_DATE),0)"LICZBA MIESIĘCY",CONCAT((TO_CHAR(ADD_MONTHS(START_DATE,3),'DD/MM/YY')),'                  ') "DATA KOŃCA OKRESU PRÓBNEGO" FROM EMP
WHERE MONTHS_BETWEEN(SYSDATE,START_DATE)<344;
--11
SELECT PRODUCT_ID "PRODUKT",TO_CHAR(RESTOCK_DATE,'DD/MM/YYYY') "DZIEŃ DOSTAWY",CONCAT(TO_CHAR(NEXT_DAY(RESTOCK_DATE,'FRIDAY'),'DD/MM/YYYY'),'        ')"PIĄTEK PO DOSTAWIE",CONCAT(TO_CHAR(LAST_DAY(RESTOCK_DATE),'DD/MM/YYYY'),'            ')"OSTATNI DZIEŃ MIESIĄCA" FROM INVENTORY
WHERE NOT RESTOCK_DATE IS NULL
ORDER BY RESTOCK_DATE;
--12
SELECT ID, TO_CHAR(START_DATE,'DD/MM/YYYY') "DATA", EXTRACT(MONTH FROM START_DATE) "MIESIĄC" FROM EMP
WHERE EXTRACT(YEAR FROM START_DATE) = '1991';
--13
SELECT ID, TO_CHAR(DATE_ORDERED, 'MM/YY') "MM/RR" FROM ORD
WHERE SALES_REP_ID = '11';
--14
SELECT LAST_NAME "NAZWISKO", TO_CHAR(START_DATE, 'DD Month YYYY', 'NLS_DATE_LANGUAGE = POLISH') || ' roku' "DATA" FROM EMP
WHERE EXTRACT(YEAR FROM START_DATE) >= 1991;